name: "deploy development"
on:
  pull_request:
    paths:
      - "src/**"
    branches:
      - "develop"
jobs:
  deploy-development:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          path: cdk-demo
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::758793629524:role/ghawker-githubworkflow-actions
          role-session-name: deploymentsession
          aws-region: eu-west-1
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'WorkshopStack'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_DEFAULT_REGION: 'eu-west-1'